environment: production
http_port: 8888
auth_secret: iwqfbiwabdhbkasfdeyuavbz

data_source_name: user=myuser password=mypassword host=ampere_2 port=5432 dbname=shortbin pool_max_conns=30 pool_min_conns=20

short_id_length:
  default: 7
  max: 15
  min: 7

expiration_in_years: 5
