environment: production
http_port: 8888
auth_secret: iwqfbiwabdhbkasfdeyuavbz

data_source_name: user=prod_user password=F7n8kd5bd host=ampere_2 port=5432 dbname=shortbin pool_max_conns=30 pool_min_conns=20

kafka:
  broker: ampere_2:9092
  topic: click_events

short_id_length:
  default: 7
  max: 15
  min: 7

expiration_in_years: 5
