environment: dev
http_port: 8888
auth_secret: sahdfbadfhblsbfasilb

data_source_name: user=dev_user password=jw8s0F4B5a host=ampere_2 port=5432 dbname=shortbin_dev pool_max_conns=10 pool_min_conns=5

kafka:
  broker: ampere_2:9092
  clicks_topic: click_events # to publish the click events of urls created by users
  public_clicks_topic: public_click_events # to publish the click events of urls created in public

short_id_length:
  default: 7
  max: 15
  min: 7

expiration_in_years: 5

redis:
  address: ampere_2:6379
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  database: 0
  ttl: 60 # minutes